### PR TITLE
Prevents shufflejank on support dialog close

### PR DESCRIPTION
**Pull request by plasticine**
untitled

### CODE REVIEW

**Comment by toolmantim** [comment]
I was like “What’s sufflejank??” until I saw the diff

**Comment by plasticine** [comment]
@toolmantim If I’d been less lazy I would have done a before GIF too 😅🙃

**Comment by toolmantim** [comment]
You mean “shufflejank” yeah 😁

**Comment by plasticine** [comment]
Urgh, lol — yes now that you point that out. My brain is not in great shape today! 🙄🧠🗑

**Comment by toolmantim** [comment]
Justin Sufflejank Morris

**Pull request merged**
