### PR TITLE
Dynamically import CodeMirror when we need it

### PR DESCRIPTION
**Pull request by keithpitt**
I took a crack at this, and this is what I came up with. I'm using `react-loader` to load in the bits when we go to show the editor.

This is what it looks like when you load the page:

jan-10-2018 14-34-00

It'll probably be tweaked when it gets on production and we start using it for real world stuff, but wasn't as hard as I thought!

### CODE REVIEW

**Comment by keithpitt** [comment]
I think I'm doing something wrong with the addons though. I think each add-on I include is also included all of it's dependencies (including bundling code mirror again):

```
                  a4ee03f14d92f01098f0.chunk.js     167 kB        8  [emitted]
           6b7f02ce9dbbf49d306db2aa55a1e442.png    50.9 kB           [emitted]
                  c5a6139d348231204eb1.chunk.js    6.37 kB        1  [emitted]
                  bd51d07588261abf25fa.chunk.js     169 kB     2, 8  [emitted]
                  9ec34777426bb96e9059.chunk.js     171 kB     3, 8  [emitted]
                  5bf791f9a72d0f5464e2.chunk.js     176 kB     4, 8  [emitted]
                  9c5e067904f568d53ee1.chunk.js     170 kB     5, 8  [emitted]
                  92d56aaad55f1da6b1c8.chunk.js     170 kB     6, 8  [emitted]
                  0e67afe1440f51459f49.chunk.js     171 kB     7, 8  [emitted]
                  b14debcd38945f371c57.chunk.js     189 kB  0, 5, 8  [emitted]
          vendor-1767481d44192e8929db.bundle.js    1.37 MB        9  [emitted]  [big]  vendor
             app-7cff818e73d30f55b9c4.bundle.js     986 kB       10  [emitted]  [big]  app
          emojis-9a3681ce36028c5e613c.bundle.js     169 kB       11  [emitted]         emojis
          public-c0ea13dddf5a5f35b1aa.bundle.js  145 bytes       12  [emitted]         public
          loader-3ca68583e9d8f9454ffa.bundle.js    1.77 kB       13  [emitted]         loader
       app-b54e3ed8ef0ae211351084bd3be5eafb.css    27.3 kB       10  [emitted]         app
    public-7b17434dc5a302c1b384ea53fdbf51bd.css    26.7 kB       12  [emitted]         public
   app-b54e3ed8ef0ae211351084bd3be5eafb.css.map  117 bytes       10  [emitted]         app
public-7b17434dc5a302c1b384ea53fdbf51bd.css.map  120 bytes       12  [emitted]         public
```

**Comment by toolmantim** [comment]
😱 This looks great!

**Comment by ticky** [comment]
I wonder if what we need is to create a “codemirror” bundle with just those modules specified?

**Comment by ticky** [comment]
I think I have a fix!

**Comment by ticky** [comment]
This is still going to fail some ESLinting but I’m going to head to the office before I look at that. Let me know if you beat me to it :smile:

**Comment by ticky** [comment]
this doesn’t seem to be returning the right bits of codemirror, but it’s returning the bundle we’re expecting at least!

**Comment by keithpitt** [comment]
Ah I see what you're doing. Rad - I did try making the bundle in the web pack config - but your idea is better.

**Comment by ticky** [comment]
I can’t figure out why Codemirror is doing weird things with its internal sizing, but the rest seems to be working now.

**Comment by toolmantim** [comment]
🎉

**Pull request merged**
