### PR TITLE
Use <Badge outlined> for team labels

### PR DESCRIPTION
**Pull request by toolmantim**
Also used in an upcoming pull request…

### CODE REVIEW

**Comment by ticky** [comment]
I wish we didn’t have that lint rule where boolean things need to be passed an actual boolean so `<Badge outlined />` was allowed :P

**Comment by toolmantim** [comment]
Yeah! Let's change it?

**Comment by ticky** [comment]
I suppose the trouble comes when you have `false` things which have to be fully qualified and it looks a bit weird? IDK.

**Comment by toolmantim** [comment]
Let’s ditch it the rule!

**Pull request merged**
