### PR TITLE
(Retry) Yarn upgrade React, Eslint & friends

### PR DESCRIPTION
**Pull request by keithpitt**
Will do some debugging in this branch to see what went wrong when it hit production.

### CODE REVIEW

**Comment by keithpitt** [comment]
Ok, found the problem. We were doing naughty things with react, and latest react says "no no"

**Comment by ticky** [comment]
That seems like a really weird thing for it to freak out about, but sure ok

**Comment by keithpitt** [comment]
@ticky oh no, that's not it (my last commit). I'm still working on the *actual* fix!

**Comment by keithpitt** [comment]
Spoiler: it's to do with using `ref` and accessing Dom elements from other react components and that we probably shouldn't be doing...

**Comment by ticky** [comment]
Ah yes, we’re probably not doing best practices there.

**Comment by keithpitt** [comment]
@ticky got it! Check out my last commit for the fix.

**Comment by ticky** [comment]
I’d love to know what changed in 16.x to break this

**Comment by keithpitt** [comment]
My guess it's the new rendering algorithm where the order of operations is slightly different.

**Comment by keithpitt** [comment]
Maybe:

> Previously, changing the ref to a component would always detach the ref before that component’s render is called. Now, we change the ref later, when applying the changes to the DOM.

**Pull request merged**
