### PR TITLE
Use a caching version of moment-duration-format

### PR DESCRIPTION
**Pull request by ticky**
This is intended to help improve performance on pages showing large quantities of timers.

Upstream PR is at jsmreese/moment-duration-format#122

### CODE REVIEW

**Review by toolmantim — APPROVED** [review]
Awesome! 🙌🏼

I wonder how we can get a before+after measure of this optimisation? 🤔

**Comment by ticky** [comment]
I don’t think we realistically can without adding some invasive data collection to our pages. If you look at the upstream PR it gives some ballpark performance numbers!

**Comment by eleanorakh** [comment]
Looks good to me! 👏 I was going to ask a similar question to Tim, but it's already been answered, so 👌🏻

**Review by eleanorakh — APPROVED** [review]

**Comment by ticky** [comment]
Went looking for a way to get some profiling info out of this. Ended up making ticky/buildkite-parallel-job-tester, and running it on localhost.

There’s a lot of data to sort through inside the profile data, but basing my profiling on filtering calls to `getDurationString`, I see the following pre-patch:

image

And the following post-patch:

image

This is sort of unscientific, but in scrolling around this a bit, I see a lot more <1ms calls with the patch, and while there are some a lot fewer >2.5ms.

Further optimisations are required, but this will drop the call time for these formatters significantly.

**Pull request merged**
