### PR TITLE
CSS assets

### PR DESCRIPTION
**Pull request by toolmantim**
This extends #156 to extract out CSS assets into a separate CSS asset file.

This means we don't need load our entire `vendor.js` just to use our stylesheets on a separate page (which is great for the new site), it gzip's slightly smaller, and the stylesheet can be loaded faster because it's 5kb gzip'd and there's a `<link>` tag in the source that the browser can independently download and parse, vs needing first to have download, parse and execute the JS bundle.

Before:

```
772K app-966928a023e1dc70d44a.js
148K app-966928a023e1dc70d44a.js.gz
182K emojis-17ac72586b5156b0492d.js
 43K emojis-17ac72586b5156b0492d.js.gz
1.5K loader-99b3342f14b9dd0df189.js
 881 loader-99b3342f14b9dd0df189.js.gz
 345 manifest.json
 34K public-1b9feb318d960011dff0.js
6.5K public-1b9feb318d960011dff0.js.gz
1.1M vendor-1a4b03e374c9dc59a24d.js
252K vendor-1a4b03e374c9dc59a24d.js.gz
```

After:

```
 27K app-aeac6aaccff19285e3dc6df65d9fe4c4.css
5.5K app-aeac6aaccff19285e3dc6df65d9fe4c4.css.gz
705K app-b09d1c636e568ca2d811.js
114K app-b09d1c636e568ca2d811.js.gz
182K emojis-17ac72586b5156b0492d.js
 43K emojis-17ac72586b5156b0492d.js.gz
1.5K loader-01c26e497d090746c800.js
 881 loader-01c26e497d090746c800.js.gz
 488 manifest.json
 159 public-c6aedf2a27719e6099e8.js
 148 public-c6aedf2a27719e6099e8.js.gz
 25K public-f82484d2cf9cb83c42cc78a41a338440.css
5.2K public-f82484d2cf9cb83c42cc78a41a338440.css.gz
1.1M vendor-1a4b03e374c9dc59a24d.js
252K vendor-1a4b03e374c9dc59a24d.js.gz
```

We'll need to update the backend to use the updated manifest to output the correct `<link>` tags wherever we were previously only loading the Javascript file.

### CODE REVIEW

**Comment by ticky** [comment]
🙌🏼 hell yes

**Comment by ticky** [comment]
(rebased against a rebased #156)

**Comment by toolmantim** [comment]
Welp! I think we lost 26a575a15836a3473d140e7dd34282a6ef493f8d in the rebase there.

**Comment by toolmantim** [comment]
Just cherry-picked it…

**Comment by ticky** [comment]
oops! sorry about that

**Comment by toolmantim** [comment]
I've had to remove the conditional (`if window._standalone`) because that won't work with CSS extraction… it might need some more testing though.

**Pull request merged**
