### PR TITLE
Tweak maintainer copy in the team member role window

### PR DESCRIPTION
**Pull request by keithpitt**
I tried this:

screen shot 2017-07-10 at 2 16 27 pm

And a slightly more verbose copy which looked a little better in the window:

screen shot 2017-07-10 at 2 15 39 pm

What do you prefer @toolmantim? I went with the longer one in this PR.

### CODE REVIEW

**Comment by keithpitt** [comment]
screen shot 2017-07-10 at 3 55 32 pm

@toolmantim how's this?

**Comment by keithpitt** [comment]
Looks like this!

screen shot 2017-07-10 at 4 14 02 pm

**Comment by toolmantim** [comment]
Let me save you the pain and I'll tweak it here locally!

**Comment by toolmantim** [comment]
It's now looking like this:

its-now-looking-like-this

Probably good to merge, then I can port it over the the Pipelines permission dropdown thing, and the user invite page, in separate PRs.

**Pull request merged**
