### PR TITLE
Feature community forum in footer

### PR DESCRIPTION
**Pull request by plasticine**
screen shot 2018-11-22 at 3 18 21 pm

### CODE REVIEW

**Comment by toolmantim** [comment]
What do you think of just “Forum” for the footer?

**Comment by keithpitt** [comment]
(I'd vote for just Forum as well...)

**Comment by plasticine** [comment]
@toolmantim @keithpitt Yepo, kinda anticipated that but was keeping it consistent with public site as I wasn’t super sure about the naming we’d want. +1 for “Forum” too though!

**Comment by toolmantim** [comment]
✈️

**Pull request merged**
