### PR TITLE
Update Agent list relay preload data

### PR DESCRIPTION
**Pull request by ticky**
Partially addresses https://3.basecamp.com/3453178/buckets/1445180/todos/323608010

### CODE REVIEW

**Comment by keithpitt** [comment]
Oh! Was the page blocking loading that extra bit of data? What even is that?

**Comment by ticky** [comment]
It’s the data used for the “You just connected an agent!” pop-up. This removes one query, though there are still unfortunately several going on on the page.

**Comment by keithpitt** [comment]
Oh right! Should we be loading that if the agent page isn't in `?setup=true` mode?

**Comment by ticky** [comment]
Hmmm, good point… I’ll see if I can make that happen instead…

**Pull request merged**
