### PR TITLE
[WIP] Pipeline settings icons

### PR DESCRIPTION
**Pull request by ticky**
New icons for the pipeline settings UI go here;

* [x] Pipeline  
  lovingly crafted based on the existing pipeline icon, but cut down for legibility at this small size

* [x] Queues

* [x] (Generic) Repository

* [x]  GitLab

* [x] Bitbucket

* [x] **Schedules**

* [x] Badges

Sketch files for the custom icons have been added to Dropbox (`design assets/app ui/Icons/Pipeline Settings 2.0`)

### CODE REVIEW

**Comment by toolmantim** [comment]
Nice one! It's exciting to get these dusted for the new pipeline settings nav!

For the Badges one, it looks a little too much like the iOS and Android checkbox/switch/toggle. Perhaps try a small check mark in the centre of the rectangle… just an abstract of "A small rectangle that shows if a thing has passed"

**Comment by ticky** [comment]
pasted_image_at_2017_05_02_05_30_pm_480
@toolmantim something like this, or just the bordered rectangle with the checkmark in the middle?

**Comment by toolmantim** [comment]
I think just the checkmark in the middle of the dark rectangle. I think it'll be easier to go with an abstract/conceptual idea of "status badge", more than a throwback to what the badges actually look like.

**Comment by ticky** [comment]
Badges has become screen shot 2017-05-03 at 11 16 53 am!

**Comment by ticky** [comment]
🆕 (Generic) Repository

**Comment by ticky** [comment]
✨ screen shot 2017-05-03 at 12 02 45 pm

**Comment by ticky** [comment]
Queues 🚶🏻‍♀️

**Comment by ticky** [comment]
🗑 Bitbucket

**Comment by toolmantim** [comment]
I didn't get a chance to review this today sorry! Will do first thing tomorrow.

**Comment by toolmantim** [comment]
Woot! Thanks for all your work pushing these forwards. I've just giving them a good once-over, and aligned them with the personal settings icons too. Going to merge this in, and then fix up the menu item labels in a separate PR.

**Pull request merged**
