### PR TITLE
Remove 2FA feature flip

### PR DESCRIPTION
**Pull request by plasticine**
:tin:

### CODE REVIEW

**Comment by eleanorakh** [comment]
I'm not seeing this in the menu? 
screen shot 2018-11-02 at 11 38 05 am

**Comment by plasticine** [comment]
@eleanorakh orly? 🤔 Defo seeing it over here!

**Comment by eleanorakh** [comment]
Yea! I signed in with the test credentials and I"m deff on the branch. Restarted server e.c.t

**Comment by ticky** [comment]
@eleanorakh is it still missing if you restart your server?

@plasticine wanna push the button? :)

**Comment by eleanorakh** [comment]
LOL I hadn't also checked out frontend 😬
all good, sorry for the confusion!

**Comment by plasticine** [comment]
@ticky Yep, was just working out what @eleanorakh was seeing — turns out all good 🙃

**Comment by ticky** [comment]
Oops!

**Pull request merged**
